---
title: 7.2.2 Resolve Target Document
---

flowchart TD

    Start@{ shape: circle, label: "Resolve Target<br>Document" } --> TraverseHistory@{ shape: subproc, label: Traverse Bitcoin<br/>Blockchain History }
    TraverseHistory --> MoreUpdates{More Updates<br>to Process?}
    MoreUpdates -->|TRUE| JSONCanonicalizeHash1@{shape: subproc, label: JSON Canonicalization<br/>and Hash}
    JSONCanonicalizeHash1 --> FindNextSignals@{shape: subproc, label: Find Next Signals}
    FindNextSignals --> ProcessBeaconSignals@{shape: subproc, label: Process Beacon Signals}
    ProcessBeaconSignals --> TargetVersionId{ update<br/>.targetVersionId }
    TargetVersionId -->| <= currentVersionId| ConfirmDupeUpdate@{shape: subproc, label: Confirm DuplicateUpdate} 
    TargetVersionId -->| = currentVersionId + 1| ApplyDidUpdate@{shape: subproc, label: Apply DID Update}
    ApplyDidUpdate --> JSONCanonicalizeHash2@{shape: subproc, label: JSON Canonicalization<br/>and Hash}
    JSONCanonicalizeHash2 --> TraverseHistory
    TargetVersionId -->| \> currentVersionId + 1| LatePublishing@{ shape: stadium, label: "LatePublishingError" }
    ConfirmDupeUpdate --> TraverseHistory

    
    MoreUpdates -->|FALSE| ReturnTargetDocument@{shape: lean-l, label: Return targetDocument}
