flowchart LR
  %% Main Actors
  Controller([DID Controller])
  Resolver([DID Resolver])

  %% Impl Libs & Apps
  subgraph SDK["Application / SDK"]
    Create[Create]
    Deactivate[Deactivate]
    Update[Update]
    Read[Read]
    KMS[Key Manager]
    Crypto[Cryptosuite]
  end

  subgraph BTC1Beacon
    SingletonBeacon
    MapBeacon
    SMTBeacon
  end

  %% Data
  BTC[(Bitcoin Blockchain)]
  CAS[("CAS (IPFS)")]
  Sidecar[(Sidecar Data)]

  %% DID Resolver
  Resolver ---> Read

  %% DID Controller
  Controller --> Create
  Controller --> Update
  Controller --> Deactivate
  
  %% Update
  Update --> KMS
  Update --> Crypto
  Update --> Sidecar

  %% Beacons
  Update --> BTC1Beacon
  BTC1Beacon --> BTC

  %% Read
  Read --> BTC
  Read --> CAS
  Read --> Sidecar
  Read --> Crypto

  %% Deactivate (Reuses Update)
  Deactivate --> Update