stateDiagram-v2
    state "Initial Document" as Initial
    state "Intermediate Document" as Intermediate
    state "Target Document" as Target
    state "Contemporary Document v1" as ContemporaryV1
    state "Contemporary Document V2" as ContemporaryV2

    [*] --> Initial: Create From<br>Deterministic Key Pair
    [*] --> Intermediate: Create From<br>External DID Document
    Intermediate --> Initial: Replace placeholder DID
    Initial --> ContemporaryV1: Resolve
    %% Stack of versioned state contemp docs
    ContemporaryV1 --> ContemporaryV2: Traverse<br>Bitcoin Blockchain
    ContemporaryV2 --> Target: 
    Target --> [*]