stateDiagram-v2
    state "Initial Document" as Initial
    state "Intermediate Document" as Intermediate
    state "Target Document" as Target
    state "Contemporary Document" as Contemporary
    state "Contemporary Document" as Contemporary2

    [*] --> Initial: Create From<br>Deterministic Key Pair
    [*] --> Intermediate: Create From<br>External DID Document
    Intermediate --> Initial: Replace placeholder DID
    Initial --> Contemporary: Resolve
    Contemporary --> Contemporary2: Traverse<br>Bitcoin Blockchain
    Contemporary2 --> Contemporary
    Contemporary2 --> Target
    Target --> [*]