---
title: 7.3.1 Construct BTCR2 Update
---

flowchart TD
    Start@{shape: circle, label: Construct<br>BTCR2 Update} --> ConstructPatch@{shape: subproc, label: Apply JSON Patch<br>to sourceDocument}
    ConstructPatch --> ValidateTargetDoc{Is targetDocument<br>conformant?}
    ValidateTargetDoc -->|TRUE|JSONCanonicalizeHash@{shape: subproc, label: JSON Canonicalization<br/>and Hash the<br>sourceDocument<br>and targetDocument}
    ValidateTargetDoc -->|FALSE|HandleError@{ shape: stadium, label: "InvalidDIDUpdateError" }
    JSONCanonicalizeHash --> End@{shape: lean-l, label: Return unsecuredBtcr2Update}