---
title: 7.3.3 Announce BTCR2 Update
---

flowchart TD
    Start@{shape: circle, label: Announce<br>BTCR2 Update} --> FindBeacons{Find<br>beaconServices}
    FindBeacons -->|NOT FOUND| BeaconNotFound@{shape: stadium, label: BeaconNotFoundError}
    FindBeacons -->|FOUND| ForEach[For each<br>beaconService]
    ForEach -->AddMoreBeacons{beaconService<br>.type}
    AddMoreBeacons -->|SingletonBeacon| BroadcastSingleton@{shape: subproc, label: Broadcast Singleton<br>Beacon Signal}
    AddMoreBeacons -->|MapBeacon| BroadcastMap@{shape: subproc, label: Broadcast Map<br>Beacon Signal}
    AddMoreBeacons -->|SMTBeacon| BroadcastSMT@{shape: subproc, label: Broadcast SMT<br>Beacon Signal}
    AddMoreBeacons -->|ELSE| InvalidBeacon@{shape: stadium, label: InvalidBeaconError}
    BroadcastSingleton --> SignalMetadata[signalMetadata]
    BroadcastMap --> SignalMetadata
    BroadcastSMT --> SignalMetadata
    SignalMetadata --> MergeSignalsMetadata[Merge<br>signalMetadata]
    SignalMetadata --> ForEach
    MergeSignalsMetadata --> Return@{shape: lean-l, label: Return<br>signalsMetadata}