---
title: 4.2.2 Resolve Target Document
---

flowchart TD

    Start@{ shape: circle, label: "Resolve Target<br>Document" } --> TraverseHistory@{ shape: subproc, label: Traverse Bitcoin<br/>Blockchain History }
    TraverseHistory --> JSONCanonicalizeHash1@{shape: subproc, label: JSON Canonicalization<br/>and Hash}
    JSONCanonicalizeHash1 --> FindNextSignals@{shape: subproc, label: Find Next Signals}
    FindNextSignals --> ProcessBeaconSignals@{shape: subproc, label: Process Beacon Signals}
    ProcessBeaconSignals --> LoopOrderedUpdates@{shape: subproc, label: For update in orderedUpdates}
    subgraph Loop
        LoopOrderedUpdates --> TargetVersionId{ update<br/>.targetVersionId }
        TargetVersionId -->| <= currentVersionId| ConfirmDupeUpdate@{shape: subproc, label: Confirm DuplicateUpdate} 
        TargetVersionId -->| = currentVersionId + 1| ApplyDidUpdate@{shape: subproc, label: Apply DID Update}
        ApplyDidUpdate --> JSONCanonicalizeHash2@{shape: subproc, label: JSON Canonicalization<br/>and Hash}
        TargetVersionId -->| \> currentVersionId + 1| LatePublishing@{ shape: stadium, label: "LatePublishingError" }
    end
    Loop --> TraverseHistory
    Loop --> ReturnTargetDocument@{shape: lean-l, label: Return targetDocument}
