---
title: 7.1 Create DID and Initial DID Document
---

flowchart TD

    Start@{ shape: circle, label: "Create DID<br/>and Initial<br/>DID Document" } --> CheckIdType{ idType }
    
    %% Deterministic
    CheckIdType -->|KEY| Deterministic@{ shape: subproc, label: "From<br/>Deterministic<br/>Key Pair" }
    Deterministic --> IdentifierEncodingK1@{ shape: subproc, label: Identifier<br/>Encoding (k1) }
    IdentifierEncodingK1 ---> ResolveDeterministic@{ shape: subproc, label: "Deterministically<br/>Generate Initial DID<br/>Document" }

    %% External
    CheckIdType -->|EXTERNAL| External@{ shape: subproc, label: "From External<br/>Intermediate<br/>DID Document" }
    External --> JSONCanonicalizeHash@{ shape: subproc, label:  JSON<br/>Canonicalization<br/>and Hash }
    JSONCanonicalizeHash --> IdentifierEncodingX1@{ shape: subproc, label: Identifier<br/>Encoding (x1) }
    IdentifierEncodingX1 --> CheckStoreOnCAS{ Store on CAS? }
    CheckStoreOnCAS -->|TRUE| StoreOnCAS@{shape: subproc, label: Store<br/>intermediateDocument<br/>on CAS (IPFS)}
    CheckStoreOnCAS -->|FALSE| Return
    StoreOnCAS --> Return

    %% Error
    CheckIdType -->|ERROR| InvalidIdType@{ shape: stadium, label: "InvalidIdType" }
  
    %%   Return
    ResolveDeterministic --> Return@{ shape: lean-l, label: "Return {did, initialDocument}" }